[package]
name = "ppargo"
version = "0.1.0"
edition = "cpp23"

[toolchain]
compiler = "clang++"
linker = "lld"

[dependencies]

[features]
packages = true
package_manager = "vcpkg"
vcpkg_root = "C:\\env\\vcpkg"

[build]
source_dir = "src"
include_dirs = ["src", "include"]
exclude = ["target/**"]
output_dir = "target/cpp"
binary_name = "argo"
