[package]
name = "ppargo"
version = "0.1.0"
edition = "cpp26"

[toolchain]
compiler = "clang++"
linker = "lld"

[dependencies]

[dev-dependencies]
catch2 = "3.12.0"

[features]
package_manager = "vcpkg"
vcpkg_root = "C:\\env\\vcpkg"

[build]
binary_name = "argo"
